[package]
name = "fuel-indexer-graphql-dyn"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Library for building executable dynamic GraphQL schemas"

[features]
default = ["json", "testing"]
json = ["dep:serde_json"]
testing = ["dep:graphql-parser"]

[dependencies]
async-graphql = { workspace = true, features = ["dynamic-schema", "dataloader"] }
async-graphql-value = { workspace = true }
async-trait = "0.1.73"
extension-trait = "1.0.2"
graphql-parser = { version = "0.4.0", optional = true }
indexmap = "2.0.0"
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"] }
thiserror = { workspace = true }
anyhow = "1.0"
lazy_static = "1.4.0"
convert_case = "0.6.0"
async-graphql-parser = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
async-graphql-parser = { workspace = true }
graphql-parser = "0.4.0"
insta = { version = "1.31.0", features = ["json", "ron"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
velcro = "0.5.4"
