[package]
name = "counter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.4"
log = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"
env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
json = "0.12"
fuel-tx = "0.9"
fuels-abigen-macro = "0.13"
fuels = "0.13"
fuel-gql-client = "0.6"
fuel-core = "0.6"
dotenv = "0.14"
rand = "0.8"
bytes = "0.4"


[workspace]
