[package]
name = "counter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
bytes = "0.4"
dotenv = "0.14"
env_logger = "0.9"
fuel-core = "0.6"
fuel-gql-client = "0.6"
fuel-tx = "0.9"
fuels = "0.15"
fuels-abigen-macro = "0.15"
json = "0.12"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[workspace]
