[package]
name = "fuel-indexer-graphql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer GraphQL"

[dependencies]
async-graphql = { version = "5.0", features = ["dynamic-schema"] }
async-graphql-parser = "5.0"
async-graphql-value = "5.0"
extension-trait = "1.0.2"
fuel-indexer-database = { workspace = true }
fuel-indexer-database-types = { workspace = true }
fuel-indexer-schema = { workspace = true, features = ["db-models"] }
fuel-indexer-types = { workspace = true }
lazy_static = "1.4"
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
fuel-indexer-lib = { workspace = true, default-features = true }
graphql-parser = "0.4.0"
insta = "1.31.0"
pretty_assertions = "0.5.0"
