[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault-deposit"

[contract-dependencies]
vault-contract = { path = "../../vault-contract" }

[dependencies]
vault_interface = { path = "../../vault-interface" }
