apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          resources:
            limits: 
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m 
              memory: 1Gi
      volumes:
      - name: postgres
        persistentVolumeClaim:
         claimName: {{ .Release.Name }}
