[workspace]
# Use the new resolver to prevent dev-deps and build-deps from enabling debugging or test features in production.
resolver = "2"
members = [
   "database/*",
   "examples/simple-native",
   "examples/simple-native/counter-rs",
   "examples/simple-wasm/simple-wasm",
   "examples/simple-wasm/simple",
   "fuel-indexer-api-server",
   "fuel-indexer-lib",
   "fuel-indexer-macros",
   "fuel-indexer-plugin",
   "fuel-indexer-schema",
   "fuel-indexer",
   "tests/e2e/composable-indexer",
   "tests/e2e/composable-indexer/composable-indexer-lib",
]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
