[workspace]
# Use the new resolver to prevent dev-deps and build-deps from enabling debugging or test features in production.
resolver = "2"
members = [
   "examples/block-explorer/explorer-index",
   "examples/simple-wasm/simple-wasm",
   "examples/native-execution/native-index",
   "examples/simple-wasm/simple",
   "fuel-indexer-api-server",
   "fuel-indexer-database",
   "fuel-indexer-database/database-types",
   "fuel-indexer-database/postgres",
   "fuel-indexer-database/sqlite",
   "fuel-indexer-lib",
   "fuel-indexer-macros",
   "fuel-indexer-plugin",
   "fuel-indexer-schema",
   "fuel-indexer-tests",
   "fuel-indexer-tests/components/indices/fuel-indexer-test",
   "fuel-indexer-tests/components/web",
   "fuel-indexer-types",
   "fuel-indexer",
]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

