# # The following is an example Fuel indexer configuration file.
# #
# # This configuration spec is intended to be used for a single instance
# # of a Fuel indexer node or service.
# #
# # For more info on how the Fuel indexer works, read the book: https://fuellabs.github.io/fuel-indexer/master/
# # or specifically read up on these configuration options: https://fuellabs.github.io/fuel-indexer/master/getting-started/configuration.html

# # Whether to allow replacing an indexer.
# #
# # If this is disabled, then an HTTP 409 Conflict will be returned if an indexer with the same name already exists.
# replace_indexer: false

# # Log level passed to the Fuel Indexer service.
# log_level: info

# # Use Prometheus metrics reporting.
# metrics: true

# # Prevent indexers from running without handling any blocks.
# stop_idle_indexers: true

# # Run database migrations before starting service.
# run_migrations: true

# # Enable verbose logging.
# verbose: false

# # Start a local Fuel node.
# local_fuel_node: false

# # Allow network configuration via indexer manifests.
# indexer_net_config: false

# The number of WASM opcodes after which the indexer will stop execution.
# metering_points: 30000000000

# # Allow the web API to accept raw SQL queries.
# accept_sql_queries: true

# # ***********************
# # Fuel Node configuration
# # ************************

# fuel_node:

#   # Host of the running Fuel node.
#   host: localhost

#   # Listening port of the running Fuel node.
#   port: 4000

# # *************************
# # GraphQL API configuration
# # *************************

# graphql_api:
#   # GraphQL API host.
#   host: localhost

#   # GraphQL API port.
#   port: 29987

#   # Max body size for GraphQL API requests.
#   max_body_size: "5242880"

# # ******************************
# # Database configuration options
# # ******************************

# database:

#   postgres:
#     # Postgres username.
#     user: postgres

#     # Postgres database.
#     database: postgres

#     # Postgres password.
#     password: password

#     # Postgres host.
#     host: localhost

#     # Postgres port.
#     port: 5432

# # ******************************
# # Indexer service authentication
# # ******************************

# authentication:
#   # Require users to authenticate for some operations.
#   enabled: false

#   # Which authentication scheme to use.
#   strategy: jwt

#   # Secret used if JWT authentication is specified.
#   jwt_secret: abcdefghijklmnopqrstuvwxyz1234567890*

#   # JWT issuer if JWT authentication is specified.
#   # jwt_issuer: FuelLabs

#   # Amount of time (seconds) before expiring token if JWT authentication is specified.
#   # jwt_expiry: 2592000

# # ********************************
# # Rate limit configuration options
# # ********************************

# rate_limit:
#   # Enable rate limiting.
#   enabled: false

#   # Maximum number of requests to allow over --rate-limit-window..
#   request_count: 10

#   # Number of seconds over which to allow --rate-limit-rps.
#   window_size: 5

