# # The following is an example Fuel indexer configuration file.
# #
# # This configuration spec is intended to be used for a single instance
# # of a Fuel indexer node or service.
# #
# # For more info on how the Fuel indexer works, read the book: https://fuellabs.github.io/fuel-indexer/master/
# # or specifically read up on these configuration options: https://fuellabs.github.io/fuel-indexer/master/getting-started/configuration.html

# # Use Prometheus metrics reporting.
# metrics: true

# # Prevent indexers from running without handling any blocks.
# stop_idle_indexers: true

# # ***********************
# # Fuel Node configuration
# # ************************

# fuel_node:

#   # Host of the running Fuel node.
#   host: 127.0.0.1

#   # Listening port of the running Fuel node.
#   port: 4000

# # *************************
# # GraphQL API configuration
# # *************************

# graphql_api:
#   # GraphQL API host.
#   host: 127.0.0.1

#   # GraphQL API port.
#   port: 29987

#   # Run database migrations before starting service.
#   run_migrations: false

#   # Max body size for GraphQL API requests.
#   max_body_size: "5242880"

# # *******************************
# # Database configuration options.
# # *******************************

# database:

#   postgres:
#     # Postgres username.
#     user: postgres

#     # Postgres database.
#     database: postgres

#     # Postgres password.
#     password: password

#     # Postgres host.
#     host: 127.0.0.1

#     # Postgres port.
#     port: 5432

# # ******************************
# # Indexer service authentication
# # ******************************

# authentication:
#   # Require users to authenticate for some operations.
#   enabled: false

#   # Which authentication scheme to use.
#   strategy: ~

#   # Secret used if JWT authentication is specified.
#   jwt_secret: ~

#   # JWT issuer if JWT authentication is specified.
#   # jwt_issuer: ~