# [target.aarch64-unknown-linux-gnu]
# dockerfile = "ci/Dockerfile.aarch64-unknown-linux-gnu-clang"
# image = "aarch64-linux-gnu"

# [target.aarch64-unknown-linux-musl]
# image = "aarch64-linux-musl"

[target.x86_64-unknown-linux-gnu]
dockerfile = "ci/Dockerfile.x86_64-unknown-linux-gnu-clang"
image = "x86_64-linux-gnu"

# [target.x86_64-unknown-linux-musl]
# dockerfile = "ci/Dockerfile.x86_64-unknown-linux-musl-clang"
# image = "x86_64-linux-musl"
