version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: my-secret
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    volumes:
      - ./pgdata:/var/lib/postgresql/indexer_db
