[package]
name = "fuel-indexer-plugin"
version = "0.1.0"
edition = "2021"
license = "BUSL-1.1"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['rlib']

[dependencies]
fuel-indexer-lib = { version = "0.1", path = "../fuel-indexer-lib", default-features = false }
fuel-indexer-schema = { version = "0.1", path = "../fuel-indexer-schema", default-features = false }
