[package]
name = "fuel-indexer-macro-utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Macro Utils"

[dependencies]
async-graphql-parser = "5.0"
async-graphql-value = "5.0"
fuel-abi-types = "0.3"
fuel-indexer-lib = { workspace = true, default-features = true }
fuels = { workspace = true }
fuels-code-gen = { version = "0.46", default-features = false }
lazy_static = "1.4"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
serde_json = { workspace = true }
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }
