[package]
name = "fuel-indexer-macro-utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Macro Utils"

[dependencies]
fuel-abi-types = "0.3"
fuel-indexer-lib = { workspace = true, default-features = true }
fuels-code-gen = { version = "0.46", default-features = false }
serde_json = { workspace = true }
