[package]
name = "fuel-indexer-bin"
version = "0.2.2"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer binary"

[[bin]]
name = "fuel-indexer"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1.0", default-features = false }
clap = { version = "4.1", features = ["derive", "env"] }
fuel-indexer = { version = "0.2", path = "../../packages/fuel-indexer" }
fuel-indexer-api-server = { version = "0.2", path = "../../packages/fuel-indexer-api-server", optional = true }
fuel-indexer-database = { version = "0.2", path = "../../packages/fuel-indexer-database" }
fuel-indexer-lib = { version = "0.2", path = "../../packages/fuel-indexer-lib" }
tokio = { version = "1.8", features = ["macros", "rt-multi-thread", "sync", "process"] }
tracing = "0.1"

[features]
default = ["api-server"]
api-server = ["fuel-indexer-api-server"]