[package]
name = "fuel-indexer"
version = "0.2.3"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer"

[dependencies]
anyhow = { version = "1.0", default-features = false }
async-std = "1"
async-trait = "0.1"
axum = { version = "0.5", features = ["multipart"] }
bincode = "1.3.3"
cfg-if = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
fuel-core-client = "0.17.2"
fuel-indexer-api-server = { version = "0.2", path = "../fuel-indexer-api-server", optional = true }
fuel-indexer-database = { version = "0.2", path = "../fuel-indexer-database" }
fuel-indexer-database-types = { version = "0.2", path = "../fuel-indexer-database/database-types" }
fuel-indexer-lib = { version = "0.2", path = "../fuel-indexer-lib" }
fuel-indexer-metrics = { version = "0.2", path = "../fuel-indexer-metrics", optional = true }
fuel-indexer-postgres = { version = "0.2", path = "../fuel-indexer-database/postgres" }
fuel-indexer-schema = { version = "0.2", path = "../fuel-indexer-schema", features = ["db-models"] }
fuel-indexer-types = { version = "0.2", path = "../fuel-indexer-types" }
fuel-tx = "0.26.0"
fuel-types = "0.26.0"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http2", "http1", "runtime" ]}
hyper-rustls = { version = "0.23", features = ["http2"] }
lazy_static = "1.4"
prometheus = { version = "0.13", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_yaml = "0.8"
sqlx = "0.6"
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread", "sync", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["env-filter"] }
wasmer = "2.0"
wasmer-compiler-cranelift = { version = "2.0" }
wasmer-engine-universal = "2.0"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
fuel-core-client = { version = "0.17.2", features = ["test-helpers"] }
fuel-crypto = "0.26.0"
fuel-types = "0.26.0"
itertools = { version = "0.10" }
rand = "0.8"

[features]
default = ["api-server", "metrics"]
api-server = ["fuel-indexer-api-server"]
metrics = [
    "fuel-indexer-metrics", 
    "prometheus"
]
