[package]
name = "fuel-indexer"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer"

[[bin]]
name = "fuel-indexer"
path = "src/bin/main.rs"

[dependencies]
anyhow = { version = "1.0", default-features = false }
async-std = "1"
async-trait = "0.1"
bincode = "1.3.3"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
fuel-core = { version = "0.17", optional = true }
fuel-core-client = "0.17"
fuel-indexer-api-server = { workspace = true, optional = true }
fuel-indexer-database = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-schema = { workspace = true, features = ["db-models"] }
fuel-indexer-types = { workspace = true }
futures = "0.3"
serde_yaml = "0.8"
sqlx = { version = "0.6", features = ["bigdecimal"] }
thiserror = "1.0"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread", "sync", "process"] }
tracing = "0.1"
wasmer = "2.3"
wasmer-compiler-cranelift = { version = "2.3" }
wasmer-engine-universal = "2.3"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
fuel-core-client = { version = "0.17.2", features = ["test-helpers"] }

[features]
default = ["api-server"]
fuel-core-lib = ["fuel-core"]
api-server = ["fuel-indexer-api-server"]
