[project]
authors = ["Rashad Alston"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuel-indexer-test"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "upgrade/fuel-core-v0.20.1" }
