# Default values for fuel indexer for environment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: fuel-indexer
  fuel_node_host: ${fuel_indexer_fuel_node_host}
  fuel_node_port: 443
  replicas: 1
  http_port: 80
  target_port: 29987
  image:
    repository: ${fuel_indexer_image_repository}
    tag: ${fuel_indexer_image_tag}
    pullPolicy: Always
  volume: 
    pvname: fuel-indexer-db-volume
    mountPath: /mnt/db/
    claimname: fuel-indexer-db-volume-pv-claim
    storageclass: ${fuel_indexer_pvc_storage_class}
    storagerequests: ${fuel_indexer_pvc_storage_requests}
    accessmodes: ReadWriteOnce
  postgres:
    host: ${postgres_host}
    database: ${postgres_database}
    port: 5432
    username: ${postgres_username}
    password: ${postgres_password}