[package]
name = "fuel-indexer-schema"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Schema"

[dependencies]
bincode = "1.3.3"
fuel-indexer-database = { workspace = true, optional = true }
fuel-indexer-database-types = { workspace = true }
fuel-indexer-graphql-parser = { workspace = true }
fuel-indexer-types = { workspace = true }
hex = "0.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = "0.9"
sqlx = { version = "0.6", optional = true, features = ["postgres", "runtime-tokio-rustls", "bigdecimal"] }
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
insta = { version = "1.8", features = ["yaml"] }

[features]
default = ["db-models"]
db-models = [
    "sqlx",
    "thiserror",
    "fuel-indexer-database",
]

