[package]
name = "fuel-indexer-schema"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Schema"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
fuel-indexer-database = { workspace = true, optional = true }
fuel-indexer-database-types = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-postgres = { workspace = true, optional = true }
fuel-indexer-types = { workspace = true }
fuel-tx = { version = "0.26.0", features = ["serde", "alloc"] }
fuel-types = { version = "0.26.0", features = ["serde", "alloc"] }
fuels-core = { version = "0.37", default-features = false }
graphql-parser = "0.3"
hex = "0.4"
itertools = { version = "0.10", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = "0.9"
sqlx = { version = "0.6", optional = true, features = ["postgres", "runtime-tokio-rustls", "bigdecimal"] }
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
insta = { version = "1.8", features = ["yaml"] }

[features]
default = ["db-models"]
db-models = [
    "sqlx",
    "itertools",
    "thiserror",
    "fuel-indexer-postgres",
    "fuel-indexer-database",
]

