[package]
name = "web-api"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
fuel-indexer-tests = { version = "0.0.0", path = "./../../../fuel-indexer-tests" }
fuel-types = { workspace = true }
tokio = { features = ["macros", "rt-multi-thread"], workspace = true }
