[package]
name = "fuel-executor"
version = "0.0.0"
edition = "2021"
license = "BUSL-1.1"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
async-std = "1.10.0"
async-trait = "0.1"
axum = "0.4"
cfg-if = "1.0"
fuel-core = { version = "0.6.4" }
fuel-gql-client = { version = "0.6.4" }
fuel-indexer-database-types = { path = "../database/database-types" }
fuel-indexer-schema = { path = "../database/schema", features = ["db-models"] }
fuel-tx = "0.9"
fuel-types = "0.3"
fuel-vm = { version = "0.8" }
fuels-core = { version = "0.15" }
futures = "0.3"
http = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-scale = "0.2"
serde_json = { version = "1.0", features = ["raw_value"] }
serde_yaml = "0.8.19"
structopt = "0.3"
sqlx = "0.6"
thiserror = "1.0"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["env-filter"] }
wasmer = "2.0"
wasmer-compiler-cranelift = { version = "2.0" }
wasmer-engine-universal = "2.0"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
fuel-core = { version = "0.6.4", features = ["test-helpers"] }
fuel-gql-client = { version = "0.6.4", features = ["test-helpers"] }
fuel-storage = { version = "0.1" }
fuel-types = "0.3"
fuels = "0.15"
fuels-abigen-macro = { version = "0.15" }
itertools = { version = "0.10" }

[features]
default = []
