[package]
name = "fuel-indexer-macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Macros"

[lib]
proc-macro = true

[dependencies]
async-graphql-parser = "5.0"
async-graphql-value = "5.0"
fuel-abi-types = "0.3"
fuel-indexer-database-types = { workspace = true }
fuel-indexer-lib = { workspace = true, default-features = true }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-indexer-types = { workspace = true }
fuels = { workspace = true }
fuels-code-gen = { version = "0.43", default-features = false }
lazy_static = "1.4"
linked_hash_set = "0.1"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
serde_json = { workspace = true }
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
# This is a workaround to avoid cyclic dependency problems. In short,
# during the publishing step, Cargo will strip dev-dependencies that
# don't have a version. This has worked for a number of high-profile crates.
# See https://github.com/rust-lang/futures-rs/pull/2305.
fuel-indexer-utils = { path = "../fuel-indexer-utils" }
fuels-macros = { version = "0.43", default-features = false }
fuels-types = { version = "0.42", default-features = false }
serde = { workspace = true }
trybuild = "1.0"

[features]
default = ["fuel-indexer-schema/db-models"]
