[package]
name = "fuel-indexer-macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Macros"

[lib]
proc-macro = true

[dependencies]
fuel-abi-types = "0.2.1"
fuel-indexer-database-types = { workspace = true }
fuel-indexer-graphql-parser = { workspace = true }
fuel-indexer-lib = { workspace = true, default-features = false }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-indexer-types = { workspace = true }
fuel-tx = "0.26.0"
fuels = { version = "0.40.0", default-features = false }
fuels-code-gen = { version = "0.40.0", default-features = false }
lazy_static = "1.4"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.5"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
fuel-indexer-plugin = { workspace = true }
fuels = { version = "0.40.0" }
fuels-macros = { version = "0.40.0", default-features = false }
fuels-types = { version = "0.40.0", default-features = false }
trybuild = "1.0"

[features]
default = ["fuel-indexer-schema/db-models"]
