[package]
name = "fuel-indexer-api-server-bin"
version = "0.2.2"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer API Server"

[[bin]]
name = "fuel-indexer-api-server"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive", "env"] }
fuel-indexer-api-server = { version = "0.2", path = "../../packages/fuel-indexer-api-server" }
fuel-indexer-database = { version = "0.2", path = "../../packages/fuel-indexer-database" }
fuel-indexer-lib = { version = "0.2", path = "../../packages/fuel-indexer-lib" }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
