[package]
name = "fuel-indexer-test"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fuel-indexer-macros = { workspace = true, default-features = false }
fuel-indexer-plugin = { workspace = true }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-tx = { workspace = true }
fuels = { workspace = true }
serde = { default-features = false, features = ["derive"], workspace = true }
sha2 = { version = "0.10" }
