[package]
name = "hello-index-native"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = { version = "0.1" }
fuel-indexer = { version = "0.3", path = "../../../packages/fuel-indexer" }
fuel-indexer-macros = { version = "0.3", path = "../../../packages/fuel-indexer-macros", default-features = false }
fuel-indexer-plugin = { version = "0.3", path = "../../../packages/fuel-indexer-plugin", features = ["native-execution"] }
fuel-indexer-schema = { version = "0.3", path = "../../../packages/fuel-indexer-schema", default-features = false }
fuel-tx = "0.23"
fuels = { version = "0.30", features = ["fuel-core-lib"] }
fuels-core = "0.30"
fuels-types = "0.30"
getrandom = { version = "0.2", features = ["js"] }
instant = { version = "0.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
