[package]
name = "fuel-indexer-postgres"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Postgres"

[dependencies]
bigdecimal = { version = "0.3" }
chrono = "0.4.24"
fuel-indexer-database-types = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-macro-utils = { workspace = true, optional = true }
fuel-indexer-metrics = { workspace = true, optional = true }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "offline", "time", "chrono", "bigdecimal"] }
tracing = { workspace = true }
uuid = { version = "1.3", features = ["v4"] }

[features]
default = ["metrics"]
metrics = ["fuel-indexer-macro-utils", "fuel-indexer-metrics"]
