[package]
name = "fuel-indexer-postgres"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Postgres"

[dependencies]
fuel-indexer-database-types = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-metrics = { workspace = true, optional = true }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "offline"] }
tracing = "0.1"

[features]
default = ["metrics"]
metrics = ["fuel-indexer-metrics"]
