[package]
name = "fuel-indexer-test"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
anyhow = "1"
fuel-indexer-utils = { workspace = true }
fuels = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
serde = { workspace = true }
