[package]
name = "fuel-indexer-database"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Database"

[dependencies]
fuel-indexer-database-types = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-postgres = { workspace = true, default-features = true }
sqlx = { version = "0.6" }
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
tracing = "0.1"
url = "2.2"
