[package]
name = "fuel_explorer"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.73.0"

[lib]
crate-type = ['cdylib']

[dependencies]
anyhow = "1"
fuel-indexer-utils = { workspace = true }
fuels = { workspace = true }
serde = { workspace = true }
