[package]
name = "fuel_explorer"
edition = { workspace = true }
publish = false
rust-version = { workspace = true }
version = "0.0.0"

[lib]
crate-type = ['cdylib']

[dependencies]
fuel-indexer-utils = { workspace = true }
fuels = { workspace = true }
serde = { workspace = true }
