[package]
name = "fuel-indexer-lib"
description = "A library used throughout various components of the Fuel Indexer serivce."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
<<<<<<< HEAD:fuel-indexer-lib/Cargo.toml
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
=======
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
>>>>>>> 46e24d9 (Implement review feedback):indexer-lib/Cargo.toml
tracing = "0.1"
