[package]
name = "hello-index"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fuel-indexer-macros = { version = "0.1", path = "../../../packages/fuel-indexer-macros", default-features = false }
fuel-indexer-plugin = { version = "0.1", path = "../../../packages/fuel-indexer-plugin" }
fuel-indexer-schema = { version = "0.1", path = "../../../packages/fuel-indexer-schema", default-features = false }
fuel-tx = "0.23"
fuels-core = "0.32"
fuels-types = "0.32"
getrandom = { version = "0.2", features = ["js"] }
instant = { version = "0.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
