[package]
name = "fuel-indexer-lib"
version = "0.1.10"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer Library"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sha2 = "0.9"
strum = { version = "0.24", default-features = false, features = ["derive"] }
tokio = { version = "1.8", features = ["time", "rt"] }
tracing = "0.1"
