[package]
name = "fuel-indexer-lib"
version = "0.2.3"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer Library"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
fuel-indexer-types = { version = "0.2", path = "../fuel-indexer-types" }
http = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sha2 = "0.9"
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.8", features = ["time", "rt"] }
tracing = "0.1"
