[package]
name = "fuel-indexer-lib"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Library"

[dependencies]
anyhow = "1.0"
async-graphql-parser = { workspace = true }
bincode = { workspace = true }
clap = { features = ["cargo", "derive", "env"], workspace = true }
http = { version = "0.2", default-features = false }
lazy_static = { version = "1.4" }
proc-macro2 = "1.0"
quote = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.8"
sha2 = "0.9"
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = { workspace = true }
tokio = { features = ["time", "rt"], workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["ansi", "json", "env-filter"] }
url = "2.3"

