FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
        binutils-aarch64-linux-gnu \
        build-essential \
        clang \
        cmake \
        gcc \
        git \
        libclang-dev \
        libpq5 \
        libpq-dev \
        lld \
        llvm \
        pkg-config \
        && apt-get clean
