[package]
name = "fuel-indexer-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Types"

[dependencies]
async-trait = { version = "0.1" }
bincode = { workspace = true }
bytes = { version = "1.4", features = ["serde"] }
fuel-tx = { workspace = true, features = ["serde"] }
fuel-types = { workspace = true }
fuels = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.9"
