[package]
name = "fuel-indexer-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Types"

[dependencies]
bincode = "1.3"
bytes = { version = "1.4", features = ["serde"] }
fuel-tx = { workspace = true, features = ["serde"] }
fuel-types = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuels = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.9"
tai64 = { version = "4.0", default-features = false, features = ["serde"] }
