[package]
name = "fuel-indexer-types"
version = "0.5.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer Types"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
fuel-tx = { version = "0.26.0", features = ["serde"] }
fuel-types = "0.26.0"
fuels-core = { version = "0.37", default-features = false }
fuels-types = { version = "0.37", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
sha2 = "0.9"
