[package]
name = "fuel-indexer-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Types"

[dependencies]
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
fuel-tx = { features = ["serde"], workspace = true }
fuel-types = { workspace = true }
fuels = { default-features = false, workspace = true }
serde = { default-features = false, features = ["derive", "alloc"], workspace = true }
sha2 = "0.9"
