apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.app.volume.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.app.volume.storagerequests }}
  storageClassName: {{ .Values.app.volume.storageclass }}

