apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  storageClassName: {{ .Values.app.volume.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
