apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
