[package]
name = "hello_indexer_native"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = { version = "0.1" }
fuel-indexer = { workspace = true }
fuel-indexer-macros = { workspace = true, default-features = false }
fuel-indexer-plugin = { workspace = true, features = ["native-execution"] }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-tx = { version = "0.26", default-features = false }
fuels = { default-features = false, workspace = true, features = ["std"] }
serde = { workspace = true }
