[package]
name = "hello_indexer_native"
edition = { workspace = true }
publish = false
rust-version = { workspace = true }
version = "0.0.0"

[dependencies]
async-trait = { version = "0.1" }
fuel-indexer = { workspace = true }
fuel-indexer-utils = { workspace = true, features = ["native-execution"] }
fuels = { workspace = true, features = ["std"] }
serde = { workspace = true }
