[package]
name = "fuel-indexer-database-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Database Types"

[dependencies]
serde = { default-features = false, features = ["derive", "alloc"], workspace = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }
