[package]
name = "fuel-indexer-database-types"
version = "0.1.9"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer Database Types"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
strum = { version = "0.24", default-features = false, features = ["derive"] }
