[package]
name = "fuel-indexer-database-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Database Types"

[dependencies]
async-graphql-parser = { workspace = true }
chrono = { version = "0.4.24", features = ["serde"] }
fuel-indexer-lib = { workspace = true }
serde = { features = ["derive", "alloc"], workspace = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }
