[package]
name = "fuel-indexer-plugin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Plugin"

[lib]
crate-type = ['rlib']

[dependencies]
anyhow = "1"
bincode = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-indexer-types = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { version = "0.10" }
sqlparser = { version = "0.35" }
