[package]
name = "fuel-indexer-plugin"
version = "0.1.11"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/FuelLabs/fuel-indexer"
description = "Fuel Indexer Plugin"

[lib]
crate-type = ['rlib']

[dependencies]
anyhow = { version = "1.0", default-features = false, optional = true }
fuel-indexer = { version = "0.1", path = "../fuel-indexer", default-features = false,  optional = true }
fuel-indexer-api-server = { version = "0.1", path = "../fuel-indexer-api-server", default-features = false, optional = true }
fuel-indexer-database = { version = "0.1", path = "../fuel-indexer-database", default-features = false, optional = true }
fuel-indexer-lib = { version = "0.1", path = "../fuel-indexer-lib", default-features = false }
fuel-indexer-schema = { version = "0.1", path = "../fuel-indexer-schema", default-features = false }
fuel-indexer-types = { version = "0.1", path = "../fuel-indexer-types" }
futures = { version = "0.3", optional = true }
tokio = { version = "1.8", features = ["macros", "rt-multi-thread", "sync", "process"], optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.2", features = ["env-filter"], optional = true }

[features]
default = ["wasm-execution"]
wasm-execution = []
native-execution = [
    "anyhow",
    "fuel-indexer",
    "fuel-indexer-api-server",
    "fuel-indexer-database",
    "tokio",
    "futures",
    "tracing-subscriber",
    "tracing",
]