[package]
name = "fuel-indexer-plugin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer Plugin"

[lib]
crate-type = ['rlib']

[dependencies]
anyhow = { version = "1.0", default-features = false, optional = true }
async-trait = { version = "0.1", optional = true }
bincode = { version = "1.3" }
fuel-indexer = { workspace = true, features = ["api-server"], optional = true }
fuel-indexer-api-server = { workspace = true, default-features = false, optional = true }
fuel-indexer-database = { workspace = true, default-features = false, optional = true }
fuel-indexer-lib = { workspace = true, default-features = false }
fuel-indexer-schema = { workspace = true, default-features = false }
fuel-indexer-types = { workspace = true }
hex = "0.4"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread", "sync", "process"], optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.2", features = ["env-filter"], optional = true }

[features]
default = []
native-execution = [
    "anyhow",
    "async-trait",
    "fuel-indexer-api-server",
    "fuel-indexer-database",
    "fuel-indexer",
    "tokio",
    "tracing-subscriber",
    "tracing",
]
