

[package]
name = "fuel-indexer-tests"
version = "0.0.0"
edition = "2021"
license = "BUSL-1.1"
publish = false
# Disable automatic test target discovery. This allows us to run all the integ tests as a single binary target (lib.rs)
# instead of each integ test file being its own compiled & linked binary which is the default behavior. Linking with
# RocksDB is expensive so we want to minimize the amount of work on ld. This is also how other projects like diesel-rs
# structure their integ tests.
autotests = false
autobenches = false

[lib]
name = "fuel_indexer_tests"
path = "src/lib.rs"

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[dependencies]
actix-service = { version = "2", default-features = false }
actix-web = { version = "4", default-features = false, features = ["macros"] }
async-std = "1"
axum = { version = "0.5", features = ["multipart"] }
chrono = { version = "0.4", features = ["serde"] }
fuel-indexer = { version = "0.4", path = "./../fuel-indexer" }
fuel-indexer-api-server = { version = "0.4", path = "./../fuel-indexer-api-server" }
fuel-indexer-database = { version = "0.4", path = "./../fuel-indexer-database" }
fuel-indexer-lib = { version = "0.4", path = "./../fuel-indexer-lib" }
fuel-indexer-postgres = { version = "0.4", path = "./../fuel-indexer-database/postgres" }
fuel-indexer-schema = { version = "0.4", path = "./../fuel-indexer-schema" }
fuel-indexer-types = { version = "0.4", path = "./../fuel-indexer-types" }
fuel-tx = "0.26.0"
fuel-types = "0.26.0"
fuels = { git = "https://github.com/FuelLabs/fuels-rs", branch = "segfault_magnet/wasm_friendly_abigen", features = ["fuel-core-lib"] }
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs", branch = "segfault_magnet/wasm_friendly_abigen", default-features = true }
fuels-macros = { git = "https://github.com/FuelLabs/fuels-rs", branch = "segfault_magnet/wasm_friendly_abigen" }
futures = "0.3"
hex = "0.4"
hyper = { version = "0.14", features = ["client", "http2", "http1", "runtime" ]}
itertools = "0.10"
lazy_static = "1.4"
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "stream", "multipart"] }
serde_json = "1.0"
serde_yaml = "0.8"
sqlx = { version = "0.6", features = ["bigdecimal"] }
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["env-filter"] }
wasmer = "2.0"
wasmer-compiler-cranelift = { version = "2.0" }
wasmer-engine-universal = "2.0"

[features]
e2e = []
postgres = []

# TODO: https://github.com/FuelLabs/fuel-indexer/issues/583
pg-embed-skip = []
