[package]
name = "fuel-indexer-api-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer API Server"

[[bin]]
name = "fuel-indexer-api-server"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0"
async-graphql = "5.0.7"
async-graphql-axum = "5.0.7"
async-std = "1"
axum = { version = "0.6", features = ["multipart", "macros"] }
clap = { features = ["cargo", "derive", "env"], workspace = true }
fuel-crypto = { version = "0.31.2", features = ["std"] }
fuel-indexer-database = { workspace = true }
fuel-indexer-graphql = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-metrics = { workspace = true, optional = true }
fuel-indexer-schema = { workspace = true, features = ["db-models"] }
futures-util = { version = "0.3", optional = true }
hex = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http2", "http1", "runtime" ] }
hyper-rustls = { version = "0.23", features = ["http2"] }
jsonwebtoken = "8"
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
sqlparser = { version = "0.35" }
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls", "bigdecimal"] }
strum = { version = "0.24", default-features = false, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4", features = ["limit", "buffer"] }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"] }
tracing = { workspace = true }

[features]
default = ["metrics"]
fuel-core-lib = []
metrics = ["fuel-indexer-metrics", "futures-util"]
