[package]
name = "fuel-indexer-api-server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Indexer API Server"

[[bin]]
name = "fuel-indexer-api-server"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0"
async-std = "1"
axum = { version = "0.6", features = ["multipart", "macros"] }
clap = { version = "3.1", features = ["cargo", "derive", "env"] }
fuel-crypto = { version = "0.27", features = ["std"] }
fuel-indexer-database = { workspace = true }
fuel-indexer-lib = { workspace = true }
fuel-indexer-metrics = { workspace = true, optional = true }
fuel-indexer-schema = { workspace = true, features = ["db-models"] }
http = "0.2"
hyper = { version = "0.14", features = ["client", "http2", "http1", "runtime" ]}
hyper-rustls = { version = "0.23", features = ["http2"] }
jsonwebtoken = "8"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls", "bigdecimal"] }
thiserror = "1.0"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4" }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"] }
tracing = "0.1"
uuid = { version = "1.3", features = ["v4"] }

[features]
default = ["metrics"]
metrics = ["fuel-indexer-metrics"]