name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test-docs:
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml
    with:
        docs-src-path: 'docs/src'
