fuel_node:
  host: 127.0.0.1
  port: 4004

graphql_api:
  host: 0.0.0.0
  port: 29987
  run_migrations: true


database:
  postgres:
    user: postgres
    database: postgres
    password: my-secret 
    host: localhost
    port: 5432

sqlite_db_path: ../main.db
